export const SET_STOCK = "SET_STOCK";
export const UPDATE_USER = "UPDATE_USER";
export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
